# Generated by Django 5.0.1 on 2024-04-18 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomsTaxonomy',
            fields=[
                ('TaxonomyID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('LevelName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('QuestionPaperID', models.AutoField(primary_key=True, serialize=False)),
                ('PaperName', models.CharField(max_length=255)),
                ('PaperCode', models.CharField(max_length=255)),
                ('ExamDate', models.DateField()),
                ('ExamTime', models.TimeField()),
                ('Department', models.CharField(max_length=255)),
                ('Semester', models.CharField(max_length=255)),
                ('TotalMarks', models.IntegerField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.categories')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='PaperSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionNumber', models.IntegerField()),
                ('SectionName', models.CharField(max_length=255)),
                ('NumMainQuestions', models.IntegerField()),
                ('TotalMarksInSection', models.IntegerField()),
                ('PaperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.questionpapers')),
            ],
        ),
        migrations.CreateModel(
            name='MainQuestions',
            fields=[
                ('MainQuestionNumber', models.IntegerField()),
                ('MainQuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('NumSubQuestions', models.IntegerField()),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.papersections')),
                ('PaperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.questionpapers')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionText', models.TextField()),
                ('Answer', models.TextField(blank=True, null=True)),
                ('OptionA', models.CharField(blank=True, max_length=255, null=True)),
                ('OptionB', models.CharField(blank=True, max_length=255, null=True)),
                ('OptionC', models.CharField(blank=True, max_length=255, null=True)),
                ('OptionD', models.CharField(blank=True, max_length=255, null=True)),
                ('CorrectOption', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit', models.CharField(blank=True, max_length=7, null=True)),
                ('Marks', models.IntegerField()),
                ('Type', models.CharField(max_length=50)),
                ('BloomTaxonomyID', models.CharField(max_length=2)),
                ('FacultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaperQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionNumber', models.IntegerField()),
                ('MainQuestionsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.mainquestions')),
                ('QuestionPaperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.questionpapers')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionpapercreation.questions')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='question_images/')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='questionpapercreation.questions')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='answer_images/')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_images', to='questionpapercreation.questions')),
            ],
        ),
        migrations.AddConstraint(
            model_name='papersections',
            constraint=models.UniqueConstraint(fields=('PaperID', 'SectionNumber'), name='unique_paper_section'),
        ),
        migrations.AlterUniqueTogether(
            name='questionpaperquestions',
            unique_together={('QuestionPaperID', 'QuestionID')},
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('QuestionText', 'Type')},
        ),
    ]
