# Generated by Django 5.0.1 on 2024-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionpapercreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyMCEAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TinyMCE API Key',
                'verbose_name_plural': 'TinyMCE API Keys',
            },
        ),
    ]
